name: Github Actions

on:
  push:
    branches: '**'
jobs:
  code-quality-macos:
    runs-on: macos-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v4
    - name: Run Rust checks
      working-directory: rust/
      run: |
        rustup update
        cargo clippy
        cargo test

  code-quality-linux:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v4
    - name: Run Rust checks
      working-directory: rust/
      run: |
        rustup update
        cargo clippy
        cargo test
