name: Github Actions

.shared_steps: &shared_steps
  steps:
    - uses: actions/checkout@v4
    - run: rustup update
on:
  push:
    branches: '**'
jobs:
  code-quality-macos:
    runs-on: macos-latest
    continue-on-error: false
    <<: *shared_steps
  code-quality-linux:
    runs-on: ubuntu-latest
    continue-on-error: false
    <<: *shared_steps
 